In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [5]:
#range function gives only integer range and arange function gives fraction range as well

In [6]:
np.zeros(5) #This generates one dimensional array of specified number of zeros i.e here 5

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(3,4) #This generates two dimensional array of specified number of zeros

TypeError: Cannot interpret '4' as a data type

In [9]:
np.zeros((3,4)) #This generates two dimensional array of specified number of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3,4,3)) #This generates three dimensional array of specified number of zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
5+np.zeros((3,4)) #5 is treated as a vector and will get add to every element

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
np.empty((4,5)) #this generates very very random small entities not exactly empty elements

array([[6.23042070e-307, 3.33776697e-307, 1.33511562e-306,
        6.23045466e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.86919513e-306, 6.23061763e-307,
        1.33511290e-306, 9.34608432e-307],
       [2.22522597e-306, 8.90109671e-307, 8.90111708e-307,
        8.34445138e-308, 8.34402698e-308]])

In [17]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.empty((4,5,3))

array([[[1.12278666e-311, 1.12279658e-311, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[7.29111868e-304, 1.83340445e-309, 9.16710320e-310],
        [3.7351362

In [19]:
np.linspace(2,6) #generates numbers between 2 and 6 points and always generates one dimensional array

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [20]:
np.linspace(2,6, 10) #this generates 10 numbers in between 2 to 6, not random numbers eaual distribution numbers

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [22]:
np.linspace(2,6, 10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [23]:
np.linspace(2,6, 10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [24]:
np.linspace(2,6, 10, endpoint=False).reshape(5,2) #endpoint false is to exclude upper bound from generated points

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [25]:
np.linspace(2,6, 10, endpoint=False, retstep=True) #This will give what step size is considered to generates points

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [26]:
np.linspace(2,6, 100, endpoint=False, retstep=True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [27]:
np.logspace(2,6) #This will give you logrithmic of a nummber

array([1.00000000e+02, 1.20679264e+02, 1.45634848e+02, 1.75751062e+02,
       2.12095089e+02, 2.55954792e+02, 3.08884360e+02, 3.72759372e+02,
       4.49843267e+02, 5.42867544e+02, 6.55128557e+02, 7.90604321e+02,
       9.54095476e+02, 1.15139540e+03, 1.38949549e+03, 1.67683294e+03,
       2.02358965e+03, 2.44205309e+03, 2.94705170e+03, 3.55648031e+03,
       4.29193426e+03, 5.17947468e+03, 6.25055193e+03, 7.54312006e+03,
       9.10298178e+03, 1.09854114e+04, 1.32571137e+04, 1.59985872e+04,
       1.93069773e+04, 2.32995181e+04, 2.81176870e+04, 3.39322177e+04,
       4.09491506e+04, 4.94171336e+04, 5.96362332e+04, 7.19685673e+04,
       8.68511374e+04, 1.04811313e+05, 1.26485522e+05, 1.52641797e+05,
       1.84206997e+05, 2.22299648e+05, 2.68269580e+05, 3.23745754e+05,
       3.90693994e+05, 4.71486636e+05, 5.68986603e+05, 6.86648845e+05,
       8.28642773e+05, 1.00000000e+06])

In [28]:
np.logspace(2,6,10) #genaretes 10 numbers

array([1.00000000e+02, 2.78255940e+02, 7.74263683e+02, 2.15443469e+03,
       5.99484250e+03, 1.66810054e+04, 4.64158883e+04, 1.29154967e+05,
       3.59381366e+05, 1.00000000e+06])

In [29]:
np.logspace(2,6,10, base=10)

array([1.00000000e+02, 2.78255940e+02, 7.74263683e+02, 2.15443469e+03,
       5.99484250e+03, 1.66810054e+04, 4.64158883e+04, 1.29154967e+05,
       3.59381366e+05, 1.00000000e+06])

In [30]:
np.logspace(2,6,10, base=2)

array([ 4.        ,  5.44316   ,  7.4069977 , 10.0793684 , 13.71590373,
       18.66446463, 25.39841683, 34.56191164, 47.03150375, 64.        ])

In [31]:
np.arange(2,8,20)

array([2])

In [32]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
a=np.arange(16).reshape(4,4)

In [35]:
a.max()

15

In [38]:
b=np.arange(4,20).reshape(4,4)

In [40]:
b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
b.max()

19

In [43]:
b=np.arange(4,40).reshape(3,6,2)

In [44]:
b

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [45]:
b.max(axis=1) #this do column wise search i.e y axis

array([[14, 15],
       [26, 27],
       [38, 39]])

In [54]:
b.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [46]:
c=np.arange(4,40).reshape(6,6)

In [51]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [52]:
c.max(axis=0) #this return row wise search result

array([34, 35, 36, 37, 38, 39])

In [53]:
c.max(axis=1) #this return column wise comparision/search result

array([ 9, 15, 21, 27, 33, 39])

In [57]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [58]:
10+c

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [59]:
c/0

C:\Users\ngupta\AppData\Local\Temp/ipykernel_1904/97081324.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [61]:
c**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [62]:
pow(c,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [63]:
pow(c,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [64]:
c**3

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [65]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [68]:
d=np.asarray([2,3,1,2,3,2])

In [69]:
c+d #Just make sure array size should be same for addition operation with at row level or at column level 

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [70]:
c+10

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [75]:
e=np.asarray([2,3,1,2,3,2]).reshape(6,1)

In [76]:
e

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [77]:
c+e

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [78]:
#another way of doing above i.e first convert from 1d to 2d array
f=d.reshape(1,-1)

In [79]:
f

array([[2, 3, 1, 2, 3, 2]])

In [80]:
f.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [81]:
f=f.T

In [82]:
c+f

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [83]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [84]:
np.sqrt(c) #square root

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [85]:
np.exp(c) #exponent

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [86]:
np.log10(c) #logrithmic of every element

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [87]:
#logspace give logrithmic of numners in between a scale and log10 will give you logrithmic of a number

In [88]:
x=np.array([1,2,3])

In [89]:
y=x #this will do the shallow copy not deep copy, it does not create new references i.e. use the same memory reference

In [90]:
y

array([1, 2, 3])

In [91]:
z=np.copy(x) #this is deep copy not shallow copy, this will create a new memory reference

In [92]:
z

array([1, 2, 3])

In [93]:
x[0]=100

In [94]:
x

array([100,   2,   3])

In [95]:
y

array([100,   2,   3])

In [96]:
z

array([1, 2, 3])

In [97]:
id(z)

2272580622832

In [98]:
id(x)

2272580622544

In [99]:
id(y)

2272580622544

In [100]:
id(x[0])

2272630019824

In [101]:
id(y[0]) #So id is identity of object which is unique object to object.

2272630019664

In [102]:
id(x[1])

2272630020560

In [103]:
id(y[1])

2272630021008

In [104]:
id(x)

2272580622544

In [105]:
id(y)

2272580622544

In [107]:
temp1 = np.array([567,345])

In [108]:
temp2=temp1

In [109]:
id(temp1)

2272625613968

In [110]:
id(temp2)

2272625613968

In [111]:
id(temp1[0])

2272624640336

In [112]:
id(temp2[0])

2272624641648

In [113]:
id(temp1[1]) == id(temp2[1])

True

In [114]:
id(temp1[0]) == id(temp2[0]) #very strage, value of Id is diff but comparision returns true
#id of list/array is same but Id of elements is diff, starage na but id comparision of elements returns true 

True

In [115]:
x = np.array([34, 45, 7])

In [116]:
x

array([34, 45,  7])

In [118]:
id(temp1[0])==id(x[0]) #now more strange? hahaha

True

In [119]:
#Task is to find out answer of this

In [120]:
c="sudh"

In [121]:
id(c) == id(x[0]) #Hint for above task

False