In [1]:
import pandas as pd

In [3]:
pd.DataFrame({
    'col1':[1,2,3,4,5],
    'col2':[45,56,67,34,34],
    'col3':"sudhanshu kumar krish ineuron one"
})

col1  col2                               col3
0     1    45  sudhanshu kumar krish ineuron one
1     2    56  sudhanshu kumar krish ineuron one
2     3    67  sudhanshu kumar krish ineuron one
3     4    34  sudhanshu kumar krish ineuron one
4     5    34  sudhanshu kumar krish ineuron one

In [4]:
"sudhanshu kumar krish ineuron one".split()

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [5]:
pd.DataFrame({
    'col1':[1,2,3,4,5],
    'col2':[45,56,67,34,34],
    'col3':"sudhanshu kumar krish ineuron one".split()
})

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [6]:
df=pd.DataFrame({
    'col1':[1,2,3,4,5],
    'col2':[45,56,67,34,34],
    'col3':"sudhanshu kumar krish ineuron one".split()
})

In [7]:
df['col1']

0    1
1    2
2    3
3    4
4    5
Name: col1, dtype: int64

In [8]:
df['col4']=df['col1']*df['col1']

In [9]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [10]:
df['col5']=df['col1']**2

In [11]:
df

col1  col2       col3  col4  col5
0     1    45  sudhanshu     1     1
1     2    56      kumar     4     4
2     3    67      krish     9     9
3     4    34    ineuron    16    16
4     5    34        one    25    25

In [12]:
df['col6']=df['col3'].str[0]

In [13]:
df

col1  col2       col3  col4  col5 col6
0     1    45  sudhanshu     1     1    s
1     2    56      kumar     4     4    k
2     3    67      krish     9     9    k
3     4    34    ineuron    16    16    i
4     5    34        one    25    25    o

In [14]:
def substitute(s):
    if s=='s':
        return s
    else:
        return 'z'
    

df['col7']=substitute(df['col3'].str[0])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [15]:
def test(a):
    return a**2

df['col4_4']=df['col1'].apply(test)

In [16]:
df

col1  col2       col3  col4  col5 col6  col4_4
0     1    45  sudhanshu     1     1    s       1
1     2    56      kumar     4     4    k       4
2     3    67      krish     9     9    k       9
3     4    34    ineuron    16    16    i      16
4     5    34        one    25    25    o      25

In [19]:
def substitute(s):
    if s=='s':
        return s
    else:
        return 'z'
    

df['col7']=df['col3'].str[0].apply(substitute)

In [20]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7
0     1    45  sudhanshu     1     1    s       1    s
1     2    56      kumar     4     4    k       4    z
2     3    67      krish     9     9    k       9    z
3     4    34    ineuron    16    16    i      16    z
4     5    34        one    25    25    o      25    z

In [21]:
def substitute(s):
    if s=='s':
        return s
    else:
        return 'z'
    

df['col7']=df['col6'].apply(substitute)

In [22]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7
0     1    45  sudhanshu     1     1    s       1    s
1     2    56      kumar     4     4    k       4    z
2     3    67      krish     9     9    k       9    z
3     4    34    ineuron    16    16    i      16    z
4     5    34        one    25    25    o      25    z

In [23]:
df['col7_1']=df['col6'].apply(lambda a: 's' if a=='s' else 'z')

In [24]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7 col7_1
0     1    45  sudhanshu     1     1    s       1    s      s
1     2    56      kumar     4     4    k       4    z      z
2     3    67      krish     9     9    k       9    z      z
3     4    34    ineuron    16    16    i      16    z      z
4     5    34        one    25    25    o      25    z      z

In [26]:
df['col7_2']=len(df['col3'])

In [27]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7 col7_1  col7_2
0     1    45  sudhanshu     1     1    s       1    s      s       5
1     2    56      kumar     4     4    k       4    z      z       5
2     3    67      krish     9     9    k       9    z      z       5
3     4    34    ineuron    16    16    i      16    z      z       5
4     5    34        one    25    25    o      25    z      z       5

In [28]:
df['col7_2']=df['col3'].apply(len)

In [29]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7 col7_1  col7_2
0     1    45  sudhanshu     1     1    s       1    s      s       9
1     2    56      kumar     4     4    k       4    z      z       5
2     3    67      krish     9     9    k       9    z      z       5
3     4    34    ineuron    16    16    i      16    z      z       7
4     5    34        one    25    25    o      25    z      z       3

In [36]:
df['col8']=df['col2'].apply(math.log())

TypeError: math.log requires 1 to 2 arguments

In [32]:
import math #or import numpy

In [33]:
math.log(10)

2.302585092994046

In [37]:
df['col8']=df['col2'].apply(math.log)

In [38]:
df

col1  col2       col3  col4  col5 col6  col4_4 col7 col7_1  col7_2  \
0     1    45  sudhanshu     1     1    s       1    s      s       9   
1     2    56      kumar     4     4    k       4    z      z       5   
2     3    67      krish     9     9    k       9    z      z       5   
3     4    34    ineuron    16    16    i      16    z      z       7   
4     5    34        one    25    25    o      25    z      z       3   

       col8  
0  3.806662  
1  4.025352  
2  4.204693  
3  3.526361  
4  3.526361

In [39]:
import numpy as np

In [40]:
l=["sudh",1,2,3,4]

In [41]:
type(l)

list

In [42]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [43]:
type(np.array(l))

numpy.ndarray

In [44]:
#you can see all integter will get upcast from int to float
np.array([3,4,5,6,3.0])

array([3., 4., 5., 6., 3.])

In [45]:
np.array([1,2],[3,4])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [46]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [47]:
a=np.array([[1,2],[3,4]])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
a[0]

array([1, 2])

In [50]:
a[1]

array([3, 4])

In [51]:
a[1][1]

4

In [52]:
a1=np.array([3,4,5,6,3.0])

In [53]:
a1[1]

4.0

In [54]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [55]:
#ndmin is n dimensional, so ndmin will create array inside array
np.array([1,2,3,4],ndmin=0)

array([1, 2, 3, 4])

In [56]:
np.array([1,2,3,4],ndmin=1)

array([1, 2, 3, 4])

In [57]:
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [58]:
np.array([1,2,3,4],ndmin=3)

array([[[1, 2, 3, 4]]])

In [59]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [60]:
np.array([1,2,3,4],ndmin=5)

array([[[[[1, 2, 3, 4]]]]])

In [61]:
a2=np.array([1,2,3,4],ndmin=4)

In [62]:
a2[0]

array([[[1, 2, 3, 4]]])

In [63]:
a2[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [64]:
a2[0][0]

array([[1, 2, 3, 4]])

In [65]:
a2[0][0][0]

array([1, 2, 3, 4])

In [66]:
#this is 4 dimensional array
a2[0][0][0][3]

4

In [67]:
a

array([[1, 2],
       [3, 4]])

In [68]:
#a is here a two dimensional aaray

In [69]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [70]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [71]:
#mat is matrix function. Matrix is at minimun is two dimensional array
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [72]:
a3=[1,2,3,4,5]

In [74]:
np.asarray(a3)

array([1, 2, 3, 4, 5])

In [75]:
np.mat(a3)

matrix([[1, 2, 3, 4, 5]])

In [76]:
np.asanyarray(a3)

array([1, 2, 3, 4, 5])

In [77]:
# by output you can see matrix is also an array and subset/subclass of array
#and here you can return type is matrix only and not converted to an array because 
#asanyarray or asarray it accepts an array type only to convert.
np.asanyarray(np.mat(a3))

matrix([[1, 2, 3, 4, 5]])

In [78]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [79]:
np.fromfunction(lambda i, j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [80]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [81]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [82]:
np.fromfunction(lambda i, j : i*j, (3,3,2), dtype=int)

TypeError: <lambda>() takes 2 positional arguments but 3 were given

In [83]:
np.mat(np.fromfunction(lambda i, j : i*j, (3,3,2), dtype=int))

TypeError: <lambda>() takes 2 positional arguments but 3 were given

In [84]:
#so you can 3d matrix is unable to create
np.mat(np.fromfunction(lambda i, j, z : i*j*z, (4,4,4), dtype=int))

ValueError: shape too large to be a matrix.

In [85]:
np.fromfunction(lambda i, j, z : i*j*z, (3,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [86]:
#3,3,2 is meaning that 3 arrays/matrix of 3 by 2 dimension
#i.e 3 dimensional array is x, y and z plane/axis i.e. 3d object

In [87]:
#it is 3 dimensional matrix/array with 4 matrixes 
np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [88]:
#this is 4 dimensional array/matrix but it very tough to visualize manually.
#It is 2 by 2 array and 3 arrays into 4 arrays or
#or 4 arrays of 3 arrays with 2 by 2 dimension 
np.fromfunction(lambda i, j, z, p : i*j*z*p, (4,3,2,2), dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [89]:
a = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype=int)

In [90]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [91]:
#gives which dimension array
a.ndim

3

In [92]:
#gives size of array i.e. total of all elements
a.size

24

In [93]:
a.shape

(4, 3, 2)

In [94]:
#array of which data type elements
a.dtype

dtype('int32')

In [95]:
#how to convert numpy array into dataframe, so you cant convert 3d array. 
#Only 2d array you can convert. To achieve this you need to reshape your array.
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [97]:
array2d = np.fromfunction(lambda i, j : i*j, (4,3), dtype=int)

In [99]:
array2d

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [98]:
pd.DataFrame(array2d)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [100]:
#create random data and convert into dataframe
np.random.rand()

0.819992051676108

In [101]:
np.random.rand(10, 4)

array([[0.58031607, 0.97366017, 0.94427678, 0.16133178],
       [0.905271  , 0.90999955, 0.82981125, 0.53190164],
       [0.13294495, 0.49392195, 0.31902307, 0.98094387],
       [0.52142153, 0.59341313, 0.46846621, 0.26166687],
       [0.60498639, 0.20802774, 0.90148687, 0.60660552],
       [0.41473514, 0.84127187, 0.949764  , 0.55033771],
       [0.73350596, 0.8424474 , 0.41082875, 0.67633011],
       [0.20211344, 0.73523908, 0.26534534, 0.73847622],
       [0.45551247, 0.19223038, 0.51364204, 0.59838323],
       [0.0026103 , 0.23283646, 0.15561364, 0.89401796]])

In [102]:
np.random.randint(10,4)

ValueError: low >= high

In [103]:
#generate random integer from 4 to 10
np.random.randint(4,10)

4

In [104]:
np.random.randint(4,10)

9

In [105]:
#average of these generated numbers will be 0 and std. daviation will be 1
# so it returns stanard ditributed numbers
np.random.randn(4,5)

array([[ 0.50359976,  0.49028268,  0.27978995,  0.83747218, -0.57423821],
       [ 0.90391947, -1.17198531, -0.41298782,  0.8438683 ,  0.77643526],
       [-0.58518548,  1.73779225, -0.06591648, -0.11439836, -0.05963334],
       [ 1.49508659,  0.03905275, -0.91307113, -1.48496853, -0.56111706]])

In [106]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.455028  0.335978  1.548711 -0.031377  0.155963
1 -0.498136  0.413594  1.075284  0.656957  2.264026
2  1.963235  0.516642  0.041081 -3.329559  0.127497
3 -0.472225  0.148403  1.010291 -0.393131  0.646476

In [107]:
a = np.fromfunction(lambda i, j, z : i*j*z, (4,3,2), dtype=int)

In [108]:
#reshape 3d array to convert into dataframe.
a.reshape(5,5) #this will give error because total elements are 24 not 25

ValueError: cannot reshape array of size 24 into shape (5,5)

In [109]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [110]:
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [111]:
a.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [112]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [114]:
a.reshape(4,2,1,3) #this will reshape into 4d array

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [115]:
a.reshape(4,2,1,3,1) #this will reshape into 5d array

array([[[[[0],
          [0],
          [0]]],


        [[[0],
          [0],
          [0]]]],



       [[[[0],
          [0],
          [0]]],


        [[[1],
          [0],
          [2]]]],



       [[[[0],
          [0],
          [0]]],


        [[[2],
          [0],
          [4]]]],



       [[[[0],
          [0],
          [0]]],


        [[[3],
          [0],
          [6]]]]])

In [116]:
#it will take by default 6 if you are putting -1. It automatically consider it as 6 
#i.e. another number which will bring 24 as total number
a.reshape(4,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [117]:
a.reshape(5,-1) #because 5 is not multiplier to 24

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [118]:
a.reshape(2,-134534)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [119]:
a.reshape(2,12)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [120]:
a.reshape(2,4,-2343)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [121]:
a.reshape(2,4,3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [122]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [123]:
#jump of 2 for range from 4 to 10
list(range(4,10,2))

[4, 6, 8]

In [124]:
list(range(4,10,.2)) #jump should be integer in pandas

TypeError: 'float' object cannot be interpreted as an integer

In [126]:
np.arange(4,10,.2) #jump/step size with floating number is possibe in numpy not in pandas

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [127]:
list(range(4,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

In [128]:
np.arange(4,10.5,2)

array([ 4.,  6.,  8., 10.])

In [129]:
np.arange(4,10.5,.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [130]:
b=np.arange(4,10.5,.2)

In [131]:
b[1:4]

array([4.2, 4.4, 4.6])

In [132]:
arr = np.random.rand(4,5)

In [133]:
arr

array([[0.03212576, 0.13382873, 0.4914876 , 0.54622766, 0.91428643],
       [0.879128  , 0.86578833, 0.44293147, 0.06701451, 0.37911783],
       [0.34233049, 0.67709109, 0.77038107, 0.95613323, 0.47675124],
       [0.9976133 , 0.76951677, 0.7627754 , 0.09256495, 0.21514684]])

In [134]:
#extract all data which is greater than .5
arr > .5

array([[False, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True,  True,  True, False],
       [ True,  True,  True, False, False]])

In [135]:
arr[arr > .5]

array([0.54622766, 0.91428643, 0.879128  , 0.86578833, 0.67709109,
       0.77038107, 0.95613323, 0.9976133 , 0.76951677, 0.7627754 ])

In [136]:
arr

array([[0.03212576, 0.13382873, 0.4914876 , 0.54622766, 0.91428643],
       [0.879128  , 0.86578833, 0.44293147, 0.06701451, 0.37911783],
       [0.34233049, 0.67709109, 0.77038107, 0.95613323, 0.47675124],
       [0.9976133 , 0.76951677, 0.7627754 , 0.09256495, 0.21514684]])

In [137]:
arr[2][2]

0.7703810722329167

In [139]:
arr[[1,2], [2]]

array([0.44293147, 0.77038107])

In [141]:
arr1=np.random.rand(8,5)

In [142]:
arr1

array([[0.55681015, 0.42832479, 0.11697364, 0.6247064 , 0.23316353],
       [0.4873815 , 0.40253111, 0.0958585 , 0.93441318, 0.50809512],
       [0.8244269 , 0.95761101, 0.04161117, 0.92779876, 0.45877212],
       [0.01021597, 0.64332653, 0.55293367, 0.99809717, 0.56467761],
       [0.03754635, 0.65651736, 0.7243036 , 0.59323458, 0.87136983],
       [0.72465324, 0.30073609, 0.01626469, 0.67110075, 0.02178195],
       [0.23993645, 0.2262052 , 0.36528011, 0.23203582, 0.21967317],
       [0.59512241, 0.68986052, 0.20946753, 0.88987002, 0.28506969]])

In [144]:
arr1[1:8,0:3]

array([[0.4873815 , 0.40253111, 0.0958585 ],
       [0.8244269 , 0.95761101, 0.04161117],
       [0.01021597, 0.64332653, 0.55293367],
       [0.03754635, 0.65651736, 0.7243036 ],
       [0.72465324, 0.30073609, 0.01626469],
       [0.23993645, 0.2262052 , 0.36528011],
       [0.59512241, 0.68986052, 0.20946753]])

In [147]:
arr1[1:8,[0,1,2]]

array([[0.4873815 , 0.40253111, 0.0958585 ],
       [0.8244269 , 0.95761101, 0.04161117],
       [0.01021597, 0.64332653, 0.55293367],
       [0.03754635, 0.65651736, 0.7243036 ],
       [0.72465324, 0.30073609, 0.01626469],
       [0.23993645, 0.2262052 , 0.36528011],
       [0.59512241, 0.68986052, 0.20946753]])

In [152]:
arr1[0][0]=100

In [153]:
arr1

array([[1.00000000e+02, 4.28324789e-01, 1.16973635e-01, 6.24706397e-01,
        2.33163528e-01],
       [4.87381500e-01, 4.02531107e-01, 9.58585011e-02, 9.34413182e-01,
        5.08095117e-01],
       [8.24426898e-01, 9.57611015e-01, 4.16111701e-02, 9.27798760e-01,
        4.58772119e-01],
       [1.02159668e-02, 6.43326530e-01, 5.52933668e-01, 9.98097167e-01,
        5.64677607e-01],
       [3.75463468e-02, 6.56517358e-01, 7.24303596e-01, 5.93234575e-01,
        8.71369831e-01],
       [7.24653241e-01, 3.00736090e-01, 1.62646940e-02, 6.71100747e-01,
        2.17819520e-02],
       [2.39936451e-01, 2.26205196e-01, 3.65280108e-01, 2.32035821e-01,
        2.19673174e-01],
       [5.95122409e-01, 6.89860517e-01, 2.09467533e-01, 8.89870022e-01,
        2.85069691e-01]])

In [154]:
a=[[1,2],[3,4]]
b=[[2,3],[4,5]]

In [155]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [156]:
a

array([[1, 2],
       [3, 4]])

In [157]:
b

array([[2, 3],
       [4, 5]])

In [158]:
a*b #This is elememts multiplication not matrix multiplication

array([[ 2,  6],
       [12, 20]])

In [159]:
#Lets do matrix multiplication
#matrix multiplication is only possible 
#if number of columns of 1st matrix and number of rows of 2nd matrix are same 
#and number of rows of 1st and number of columns of 2nd matrix are same
a@b #This is matrix multiplication

array([[10, 13],
       [22, 29]])

In [160]:
m=a@b

In [161]:
m/0 #this will give array of infinity value into elements 

C:\Users\ngupta\AppData\Local\Temp/ipykernel_9712/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])